name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Desplegar cuando se haga un push a la rama main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Navigate to the correct directory
        working-directory: ./client/password-generator
        run: |
          echo "Working directory changed to PasswordGenie/client/password-generator"

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  

      - name: Install dependencies
        run: npm install

      - name: Build the Angular app
        run: ng build -- --configuration production --output-path=docs --base-href=/PasswordGenie/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
